import { useState } from 'react'
import { motion } from 'framer-motion'
import { Scan, AlertTriangle, RotateCcw, Shield } from 'lucide-react'
import { api } from '../lib/api'

export default function AiDetector() {
  const [input, setInput] = useState('')
  const [result, setResult] = useState<{ score: number; analysis: string } | null>(null)
  const [loading, setLoading] = useState(false)

  const handleAnalyze = async () => {
    if (!input.trim() || input.trim().length < 100) {
      setResult({ score: -1, analysis: 'Please enter at least 100 characters for meaningful analysis.' })
      return
    }
    setLoading(true)
    try {
      const res = await api.aiChat(
        [{ sender: 'user', text: `Analyze this text and estimate the probability (0-100) that it was written by AI. Consider: repetitive phrasing, overly uniform sentence length, lack of personal voice, generic transitions, and predictable structure. Respond ONLY in this exact format:\n\nScore: [number]\nAnalysis: [2-3 sentence explanation]\n\nText to analyze:\n${input}` }],
        'AI Detector tool'
      )
      const text = res.response || ''
      const scoreMatch = text.match(/Score:\s*(\d+)/i)
      const analysisMatch = text.match(/Analysis:\s*(.+)/is)
      const score = scoreMatch ? Math.min(100, Math.max(0, parseInt(scoreMatch[1]))) : 50
      const analysis = analysisMatch ? analysisMatch[1].trim() : 'Analysis could not be generated.'
      setResult({ score, analysis })
    } catch {
      setResult({ score: -1, analysis: 'Service temporarily unavailable. Please try again.' })
    } finally {
      setLoading(false)
    }
  }

  const getScoreColor = (score: number) => {
    if (score < 0) return 'text-slate-400'
    if (score < 30) return 'text-green-500'
    if (score < 60) return 'text-yellow-500'
    return 'text-red-500'
  }

  const getScoreBg = (score: number) => {
    if (score < 0) return 'bg-slate-100 dark:bg-slate-800'
    if (score < 30) return 'bg-green-100 dark:bg-green-900/30'
    if (score < 60) return 'bg-yellow-100 dark:bg-yellow-900/30'
    return 'bg-red-100 dark:bg-red-900/30'
  }

  const getScoreLabel = (score: number) => {
    if (score < 0) return 'Waiting...'
    if (score < 30) return 'Likely Human'
    if (score < 60) return 'Uncertain'
    return 'Likely AI'
  }

  return (
    <div className="min-h-[100dvh] pt-28 pb-20 px-4 md:px-6 bg-slate-50 dark:bg-slate-950">
      <div className="max-w-[800px] mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
          <div className="flex items-center gap-2 mb-2">
            <Shield size={20} className="text-yellow-600 dark:text-yellow-400" />
            <span className="text-xs font-bold uppercase tracking-[0.2em] text-yellow-600 dark:text-yellow-400">AI TOOL</span>
          </div>
          <h1 className="text-3xl md:text-5xl font-bold tracking-tight mb-2">AI Detector</h1>
          <p className="text-base text-slate-500 dark:text-slate-400">
            Analyze text to estimate the likelihood it was generated by AI.
          </p>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="glass-card p-5 mb-5">
          <textarea
            value={input}
            onChange={e => setInput(e.target.value)}
            placeholder="Paste text to analyze (minimum 100 characters for best results)..."
            className="w-full min-h-[200px] p-4 rounded-2xl text-sm resize-none outline-none bg-white/50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 focus:border-yellow-400 transition-colors"
          />
          <div className="flex items-center justify-between mt-3">
            <span className="text-xs text-slate-400">{input.length} characters</span>
            <div className="flex gap-2">
              <button onClick={() => { setInput(''); setResult(null) }} className="pill-btn pill-btn-ghost text-xs">
                <RotateCcw size={12} /> Clear
              </button>
              <button
                onClick={handleAnalyze}
                disabled={loading || input.trim().length < 100}
                className="pill-btn pill-btn-primary text-xs disabled:opacity-50"
              >
                {loading ? 'Analyzing...' : <><Scan size={12} className="mr-1" /> Analyze</>}
              </button>
            </div>
          </div>
        </motion.div>

        {result && result.score >= 0 && (
          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="glass-card p-6 text-center">
            <div className={`w-24 h-24 rounded-full flex items-center justify-center mx-auto mb-4 ${getScoreBg(result.score)}`}>
              <span className={`text-3xl font-extrabold ${getScoreColor(result.score)}`}>{result.score}%</span>
            </div>
            <p className={`text-lg font-semibold mb-2 ${getScoreColor(result.score)}`}>{getScoreLabel(result.score)}</p>
            <p className="text-sm text-slate-500 dark:text-slate-400 max-w-md mx-auto">{result.analysis}</p>
            <div className="mt-4 flex items-center gap-1 justify-center text-xs text-slate-400">
              <AlertTriangle size={10} />
              This is an estimate, not definitive proof. Use as a guide only.
            </div>
          </motion.div>
        )}

        {result && result.score < 0 && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="glass-card p-5 text-center text-sm text-slate-500">
            {result.analysis}
          </motion.div>
        )}
      </div>
    </div>
  )
}
